// Code generated by ent, DO NOT EDIT.

package domain

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/devcui/ncepu-cs-project/domain/enrollmentstatus"
	"github.com/devcui/ncepu-cs-project/domain/student"
)

// EnrollmentStatus is the model entity for the EnrollmentStatus schema.
type EnrollmentStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 学籍状态名称
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnrollmentStatusQuery when eager-loading is set.
	Edges                     EnrollmentStatusEdges `json:"edges"`
	enrollment_status_student *int
}

// EnrollmentStatusEdges holds the relations/edges for other nodes in the graph.
type EnrollmentStatusEdges struct {
	// Student holds the value of the student edge.
	Student *Student `json:"student,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StudentOrErr returns the Student value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnrollmentStatusEdges) StudentOrErr() (*Student, error) {
	if e.loadedTypes[0] {
		if e.Student == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: student.Label}
		}
		return e.Student, nil
	}
	return nil, &NotLoadedError{edge: "student"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EnrollmentStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enrollmentstatus.FieldID:
			values[i] = new(sql.NullInt64)
		case enrollmentstatus.FieldName:
			values[i] = new(sql.NullString)
		case enrollmentstatus.ForeignKeys[0]: // enrollment_status_student
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EnrollmentStatus", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EnrollmentStatus fields.
func (es *EnrollmentStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enrollmentstatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			es.ID = int(value.Int64)
		case enrollmentstatus.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				es.Name = value.String
			}
		case enrollmentstatus.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field enrollment_status_student", value)
			} else if value.Valid {
				es.enrollment_status_student = new(int)
				*es.enrollment_status_student = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryStudent queries the "student" edge of the EnrollmentStatus entity.
func (es *EnrollmentStatus) QueryStudent() *StudentQuery {
	return NewEnrollmentStatusClient(es.config).QueryStudent(es)
}

// Update returns a builder for updating this EnrollmentStatus.
// Note that you need to call EnrollmentStatus.Unwrap() before calling this method if this EnrollmentStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (es *EnrollmentStatus) Update() *EnrollmentStatusUpdateOne {
	return NewEnrollmentStatusClient(es.config).UpdateOne(es)
}

// Unwrap unwraps the EnrollmentStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (es *EnrollmentStatus) Unwrap() *EnrollmentStatus {
	_tx, ok := es.config.driver.(*txDriver)
	if !ok {
		panic("domain: EnrollmentStatus is not a transactional entity")
	}
	es.config.driver = _tx.drv
	return es
}

// String implements the fmt.Stringer.
func (es *EnrollmentStatus) String() string {
	var builder strings.Builder
	builder.WriteString("EnrollmentStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", es.ID))
	builder.WriteString("name=")
	builder.WriteString(es.Name)
	builder.WriteByte(')')
	return builder.String()
}

// EnrollmentStatusSlice is a parsable slice of EnrollmentStatus.
type EnrollmentStatusSlice []*EnrollmentStatus
