// Code generated by ent, DO NOT EDIT.

package domain

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/devcui/ncepu-cs-project/domain/enrollmentstatus"
	"github.com/devcui/ncepu-cs-project/domain/predicate"
)

// EnrollmentStatusDelete is the builder for deleting a EnrollmentStatus entity.
type EnrollmentStatusDelete struct {
	config
	hooks    []Hook
	mutation *EnrollmentStatusMutation
}

// Where appends a list predicates to the EnrollmentStatusDelete builder.
func (esd *EnrollmentStatusDelete) Where(ps ...predicate.EnrollmentStatus) *EnrollmentStatusDelete {
	esd.mutation.Where(ps...)
	return esd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (esd *EnrollmentStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, EnrollmentStatusMutation](ctx, esd.sqlExec, esd.mutation, esd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (esd *EnrollmentStatusDelete) ExecX(ctx context.Context) int {
	n, err := esd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (esd *EnrollmentStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enrollmentstatus.Table, sqlgraph.NewFieldSpec(enrollmentstatus.FieldID, field.TypeInt))
	if ps := esd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, esd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	esd.mutation.done = true
	return affected, err
}

// EnrollmentStatusDeleteOne is the builder for deleting a single EnrollmentStatus entity.
type EnrollmentStatusDeleteOne struct {
	esd *EnrollmentStatusDelete
}

// Where appends a list predicates to the EnrollmentStatusDelete builder.
func (esdo *EnrollmentStatusDeleteOne) Where(ps ...predicate.EnrollmentStatus) *EnrollmentStatusDeleteOne {
	esdo.esd.mutation.Where(ps...)
	return esdo
}

// Exec executes the deletion query.
func (esdo *EnrollmentStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := esdo.esd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enrollmentstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (esdo *EnrollmentStatusDeleteOne) ExecX(ctx context.Context) {
	if err := esdo.Exec(ctx); err != nil {
		panic(err)
	}
}
