// Code generated by ent, DO NOT EDIT.

package domain

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/devcui/ncepu-cs-project/domain/enrollmentstatus"
	"github.com/devcui/ncepu-cs-project/domain/student"
)

// EnrollmentStatusCreate is the builder for creating a EnrollmentStatus entity.
type EnrollmentStatusCreate struct {
	config
	mutation *EnrollmentStatusMutation
	hooks    []Hook
}

// SetStudentID sets the "student" edge to the Student entity by ID.
func (esc *EnrollmentStatusCreate) SetStudentID(id int) *EnrollmentStatusCreate {
	esc.mutation.SetStudentID(id)
	return esc
}

// SetNillableStudentID sets the "student" edge to the Student entity by ID if the given value is not nil.
func (esc *EnrollmentStatusCreate) SetNillableStudentID(id *int) *EnrollmentStatusCreate {
	if id != nil {
		esc = esc.SetStudentID(*id)
	}
	return esc
}

// SetStudent sets the "student" edge to the Student entity.
func (esc *EnrollmentStatusCreate) SetStudent(s *Student) *EnrollmentStatusCreate {
	return esc.SetStudentID(s.ID)
}

// Mutation returns the EnrollmentStatusMutation object of the builder.
func (esc *EnrollmentStatusCreate) Mutation() *EnrollmentStatusMutation {
	return esc.mutation
}

// Save creates the EnrollmentStatus in the database.
func (esc *EnrollmentStatusCreate) Save(ctx context.Context) (*EnrollmentStatus, error) {
	return withHooks[*EnrollmentStatus, EnrollmentStatusMutation](ctx, esc.sqlSave, esc.mutation, esc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (esc *EnrollmentStatusCreate) SaveX(ctx context.Context) *EnrollmentStatus {
	v, err := esc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (esc *EnrollmentStatusCreate) Exec(ctx context.Context) error {
	_, err := esc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (esc *EnrollmentStatusCreate) ExecX(ctx context.Context) {
	if err := esc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (esc *EnrollmentStatusCreate) check() error {
	return nil
}

func (esc *EnrollmentStatusCreate) sqlSave(ctx context.Context) (*EnrollmentStatus, error) {
	if err := esc.check(); err != nil {
		return nil, err
	}
	_node, _spec := esc.createSpec()
	if err := sqlgraph.CreateNode(ctx, esc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	esc.mutation.id = &_node.ID
	esc.mutation.done = true
	return _node, nil
}

func (esc *EnrollmentStatusCreate) createSpec() (*EnrollmentStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &EnrollmentStatus{config: esc.config}
		_spec = sqlgraph.NewCreateSpec(enrollmentstatus.Table, sqlgraph.NewFieldSpec(enrollmentstatus.FieldID, field.TypeInt))
	)
	if nodes := esc.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enrollmentstatus.StudentTable,
			Columns: []string{enrollmentstatus.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.enrollment_status_student = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnrollmentStatusCreateBulk is the builder for creating many EnrollmentStatus entities in bulk.
type EnrollmentStatusCreateBulk struct {
	config
	builders []*EnrollmentStatusCreate
}

// Save creates the EnrollmentStatus entities in the database.
func (escb *EnrollmentStatusCreateBulk) Save(ctx context.Context) ([]*EnrollmentStatus, error) {
	specs := make([]*sqlgraph.CreateSpec, len(escb.builders))
	nodes := make([]*EnrollmentStatus, len(escb.builders))
	mutators := make([]Mutator, len(escb.builders))
	for i := range escb.builders {
		func(i int, root context.Context) {
			builder := escb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnrollmentStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, escb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, escb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, escb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (escb *EnrollmentStatusCreateBulk) SaveX(ctx context.Context) []*EnrollmentStatus {
	v, err := escb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (escb *EnrollmentStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := escb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (escb *EnrollmentStatusCreateBulk) ExecX(ctx context.Context) {
	if err := escb.Exec(ctx); err != nil {
		panic(err)
	}
}
