// Code generated by ent, DO NOT EDIT.

package domain

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/devcui/ncepu-cs-project/domain/class"
	"github.com/devcui/ncepu-cs-project/domain/department"
	"github.com/devcui/ncepu-cs-project/domain/major"
	"github.com/devcui/ncepu-cs-project/domain/student"
)

// MajorCreate is the builder for creating a Major entity.
type MajorCreate struct {
	config
	mutation *MajorMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mc *MajorCreate) SetName(s string) *MajorCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetCode sets the "code" field.
func (mc *MajorCreate) SetCode(s string) *MajorCreate {
	mc.mutation.SetCode(s)
	return mc
}

// SetDescription sets the "description" field.
func (mc *MajorCreate) SetDescription(s string) *MajorCreate {
	mc.mutation.SetDescription(s)
	return mc
}

// SetDepartmentID sets the "department" edge to the Department entity by ID.
func (mc *MajorCreate) SetDepartmentID(id int) *MajorCreate {
	mc.mutation.SetDepartmentID(id)
	return mc
}

// SetNillableDepartmentID sets the "department" edge to the Department entity by ID if the given value is not nil.
func (mc *MajorCreate) SetNillableDepartmentID(id *int) *MajorCreate {
	if id != nil {
		mc = mc.SetDepartmentID(*id)
	}
	return mc
}

// SetDepartment sets the "department" edge to the Department entity.
func (mc *MajorCreate) SetDepartment(d *Department) *MajorCreate {
	return mc.SetDepartmentID(d.ID)
}

// AddStudentIDs adds the "student" edge to the Student entity by IDs.
func (mc *MajorCreate) AddStudentIDs(ids ...int) *MajorCreate {
	mc.mutation.AddStudentIDs(ids...)
	return mc
}

// AddStudent adds the "student" edges to the Student entity.
func (mc *MajorCreate) AddStudent(s ...*Student) *MajorCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mc.AddStudentIDs(ids...)
}

// AddClasIDs adds the "class" edge to the Class entity by IDs.
func (mc *MajorCreate) AddClasIDs(ids ...int) *MajorCreate {
	mc.mutation.AddClasIDs(ids...)
	return mc
}

// AddClass adds the "class" edges to the Class entity.
func (mc *MajorCreate) AddClass(c ...*Class) *MajorCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return mc.AddClasIDs(ids...)
}

// Mutation returns the MajorMutation object of the builder.
func (mc *MajorCreate) Mutation() *MajorMutation {
	return mc.mutation
}

// Save creates the Major in the database.
func (mc *MajorCreate) Save(ctx context.Context) (*Major, error) {
	return withHooks[*Major, MajorMutation](ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MajorCreate) SaveX(ctx context.Context) *Major {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MajorCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MajorCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MajorCreate) check() error {
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`domain: missing required field "Major.name"`)}
	}
	if _, ok := mc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`domain: missing required field "Major.code"`)}
	}
	if _, ok := mc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`domain: missing required field "Major.description"`)}
	}
	return nil
}

func (mc *MajorCreate) sqlSave(ctx context.Context) (*Major, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MajorCreate) createSpec() (*Major, *sqlgraph.CreateSpec) {
	var (
		_node = &Major{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(major.Table, sqlgraph.NewFieldSpec(major.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.Name(); ok {
		_spec.SetField(major.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mc.mutation.Code(); ok {
		_spec.SetField(major.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := mc.mutation.Description(); ok {
		_spec.SetField(major.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := mc.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   major.DepartmentTable,
			Columns: []string{major.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.major_department = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   major.StudentTable,
			Columns: []string{major.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   major.ClassTable,
			Columns: []string{major.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MajorCreateBulk is the builder for creating many Major entities in bulk.
type MajorCreateBulk struct {
	config
	builders []*MajorCreate
}

// Save creates the Major entities in the database.
func (mcb *MajorCreateBulk) Save(ctx context.Context) ([]*Major, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Major, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MajorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MajorCreateBulk) SaveX(ctx context.Context) []*Major {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MajorCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MajorCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
