// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authorization is the predicate function for authorization builders.
type Authorization func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
